### ISSUE TITLE
TypeError: undefined is not a function

### ISSUE THREAD

**Issue by kgashok** [larsthorup/jsdevenv-jasmine#2]
I am trying to test some Ajax call within my code using your repo, and getting an issue very similar to https://github.com/gruntjs/grunt-contrib-jasmine/issues/113. 

I've made changes as suggested in SO answer as well (using the 2nd option) - http://stackoverflow.com/questions/4662641/how-do-i-verify-jquery-ajax-events-with-jasmine

And by the way, should the https://github.com/larsthorup/jsdevenv-jasmine/blob/master/src/lib/jquery.js file be updated to the latest version? 

What should I change? Here is my current snapshot of a fork of your repo - https://github.com/kgashok/jsdevenv-jasmine

**Comment by larsthorup** [comment]
I have looked at the code in your repository. I rewrote your failing test to this, trying to keep your style:
```
  it('should return 174 for kgashok', function (done) {
    function getProduct (id, callback) {
      $.ajax({
        type: "GET",
        url: "data.json",
        contentType: "application/json; charset=utf-8",
        dataType: "json",
        success: callback
      });
    }

    spyOn($, 'ajax').and.callFake(function (options) {
      options.success(174);
    });

    getProduct('123', function (result) {
      expect(result).toBe(174);
      done();
    });
  });
``` 

Note 
* getProduct returns its result via the callback
* so the expect() goes inside the callback that receives this result
* passing done() to tell Jasmine that this is an asynchronous test and calling done() when done

Hope this helps!

**Comment by kgashok** [comment]
Thanks much! I made the changes as suggested by you, and updated my repo (https://github.com/kgashok/jsdevenv-jasmine). 

My `grunt test` completes successfully locally. However, when I run `grunt coverage`, I get the following error: 

```
 ReferenceError: Can't find variable: $ in file:///home/ashokb/hero/jasmine/src/js/util/getBrownies.test.js (line 22) (1)
```

Thanks for your help!

**Comment by larsthorup** [comment]
Add this line in `Gruntfile.js` around line 74 to ensure that jQuery is loaded, also when running code coverage:
```
            vendor: gruntConfig.jasmine.src.options.vendor,
```

**Comment by kgashok** [comment]
Super! Appreciate your quick feedback. I've updated my repo and now works both in `test` and `coverage`. 

One last thing: I changed my test (https://github.com/kgashok/jsdevenv-jasmine/blob/master/src/js/util/getBrownies.test.js) to actually make the Ajax call - in that case, the test case fails (consistently in both `grunt test` and `grunt coverage`). 

What am I missing?

**Comment by larsthorup** [comment]
Your original function (getBrownies) should take a callback, and instead of returning the result directly, should call the callback with the result, just like the small example function you had in your test. And then you need to adapt your test to expect() inside the callback, instead of expect() on the return value, again just like you had previously when your test was working. Being asynchronous like this, and requiring a callback, is an essential part of working with Ajax.

**Comment by kgashok** [comment]
Would you mind providing the code itself? I learn better by example. Thanks!

**Comment by larsthorup** [comment]
It's your coding, and you're almost there, I am sure you can get it to work from here :)

**Comment by kgashok** [comment]
Fair enough, will give it a shot!

**Comment by kgashok** [comment]
Just curious: How come in the other repo jsdevenv repo (https://github.com/kgisl/FCC-Status/blob/master/src/js/util/getBrownies.test.js), the test is able to invoke the original `getBrownies` function and the Ajax call works **as-is**, at least for `grunt test`?

**Comment by larsthorup** [comment]
Because you have passed `async: false` in you call to `$.ajax()`.

**Comment by kgashok** [comment]
But I pass `async: false` for the test in this repo as well. Don't I?

**Comment by larsthorup** [comment]
But you shouldn't. Ajax is meant to be async

On Sun, Jun 5, 2016, 6:26 PM kgashok <notifications@github.com> wrote:

> But I pass async: false for the test in this repo as well. Don't I?
>
> —
> You are receiving this because you modified the open/close state.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/larsthorup/jsdevenv-jasmine/issues/2#issuecomment-223822455>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABJbD0e-uaudcp2rcafAbvlY2ngAk5jLks5qIvjPgaJpZM4Itgyw>
> .
>
-- 
Lars Thorup, +45 6068 0968, https://careers.stackoverflow.com/larsthorup

**Comment by kgashok** [comment]
I've modified my test file to match your recommendations (https://github.com/kgashok/jsdevenv-jasmine/blob/master/src/js/util/getBrownies.test.js). I have commented out the `spyOn` code, so I can do the actual Ajax call. 

I get the following errors (even with `jasmine.DEFAULT_TIMEOUT_INTERVAL = 10000`): 

```
 util/getBrownies
   - successful ajax request...
log: ERROR **** [object Object]error
   X successful ajax request
     Expected 0 to be 1. (1)
     Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL. (2)

```

Please help!

**Comment by larsthorup** [comment]
I am confused about what you are trying to do here. Your getProduct() function should be in getBrownies.js, not in getBrownies.test.js. Furthermore, since this is a unit test, not an end-to-end test, you do not actually want to do the Ajax call. So the spyOn need to be there when running the test. The actual Ajax call should only happen when you are running this code in production.

The purpose of unit test is to test code in isolation, in this case: only testing the front-end code, not involving the back-end code. So keep the spyOn() in there.

**Comment by kgashok** [comment]
Got it! I do intend to move the `getProduct` code out of the test file soon. 

But if I were to do an **end-to-end test**, what changes would I have to make?

**Comment by larsthorup** [comment]
End-to-end testing is a completely different ball game. A good tool is http://nightwatchjs.org/. End-to-end testing does have a lot of problems in general though, so you should keep those to a minimum and focus on unit tests, which are fast, robust and precise. For an advanced approach where you get the benefits of both unit tests and integration tests, see my blog posts: http://zealake.com/2015/01/05/unit-test-your-service-integration-layer/ and http://zealake.com/2016/03/20/dont-let-your-mocks-lie-to-you/
